//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.22 at 07:02:58 PM ICT 
//


package com.buckwa.ws.newws.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for faculty complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="faculty">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="faculty_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="faculty_tname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="faculty_ename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="icl_faculty_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="brief" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "faculty", propOrder = {
    "facultyId",
    "facultyTname",
    "facultyEname",
    "iclFacultyId",
    "brief"
})
public class Faculty {

    @XmlElement(name = "faculty_id")
    protected String facultyId;
    @XmlElement(name = "faculty_tname")
    protected String facultyTname;
    @XmlElement(name = "faculty_ename")
    protected String facultyEname;
    @XmlElement(name = "icl_faculty_id")
    protected String iclFacultyId;
    protected String brief;

    /**
     * Gets the value of the facultyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacultyId() {
        return facultyId;
    }

    /**
     * Sets the value of the facultyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacultyId(String value) {
        this.facultyId = value;
    }

    /**
     * Gets the value of the facultyTname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacultyTname() {
        return facultyTname;
    }

    /**
     * Sets the value of the facultyTname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacultyTname(String value) {
        this.facultyTname = value;
    }

    /**
     * Gets the value of the facultyEname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacultyEname() {
        return facultyEname;
    }

    /**
     * Sets the value of the facultyEname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacultyEname(String value) {
        this.facultyEname = value;
    }

    /**
     * Gets the value of the iclFacultyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIclFacultyId() {
        return iclFacultyId;
    }

    /**
     * Sets the value of the iclFacultyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIclFacultyId(String value) {
        this.iclFacultyId = value;
    }

    /**
     * Gets the value of the brief property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrief() {
        return brief;
    }

    /**
     * Sets the value of the brief property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrief(String value) {
        this.brief = value;
    }

}
