//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.17 at 08:04:19 PM ICT 
//


package com.buckwa.ws.newws.oxm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.buckwa.ws.newws.oxm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.buckwa.ws.newws.oxm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetSubject }
     * 
     */
    public GetSubject createGetSubject() {
        return new GetSubject();
    }

    /**
     * Create an instance of {@link GetFacultyListResponse }
     * 
     */
    public GetFacultyListResponse createGetFacultyListResponse() {
        return new GetFacultyListResponse();
    }

    /**
     * Create an instance of {@link Faculty }
     * 
     */
    public Faculty createFaculty() {
        return new Faculty();
    }

    /**
     * Create an instance of {@link GetDepartmentListResponse }
     * 
     */
    public GetDepartmentListResponse createGetDepartmentListResponse() {
        return new GetDepartmentListResponse();
    }

    /**
     * Create an instance of {@link Department }
     * 
     */
    public Department createDepartment() {
        return new Department();
    }

    /**
     * Create an instance of {@link GetFacultyList }
     * 
     */
    public GetFacultyList createGetFacultyList() {
        return new GetFacultyList();
    }

    /**
     * Create an instance of {@link GetTeachTable }
     * 
     */
    public GetTeachTable createGetTeachTable() {
        return new GetTeachTable();
    }

    /**
     * Create an instance of {@link GetTeachTableResponse }
     * 
     */
    public GetTeachTableResponse createGetTeachTableResponse() {
        return new GetTeachTableResponse();
    }

    /**
     * Create an instance of {@link TeachTable }
     * 
     */
    public TeachTable createTeachTable() {
        return new TeachTable();
    }

    /**
     * Create an instance of {@link GetSubjectResponse }
     * 
     */
    public GetSubjectResponse createGetSubjectResponse() {
        return new GetSubjectResponse();
    }

    /**
     * Create an instance of {@link Subject }
     * 
     */
    public Subject createSubject() {
        return new Subject();
    }

    /**
     * Create an instance of {@link GetTeacherofSubjectResponse }
     * 
     */
    public GetTeacherofSubjectResponse createGetTeacherofSubjectResponse() {
        return new GetTeacherofSubjectResponse();
    }

    /**
     * Create an instance of {@link LectureTeacher }
     * 
     */
    public LectureTeacher createLectureTeacher() {
        return new LectureTeacher();
    }

    /**
     * Create an instance of {@link PracticeTeacher }
     * 
     */
    public PracticeTeacher createPracticeTeacher() {
        return new PracticeTeacher();
    }

    /**
     * Create an instance of {@link UnknownTeacher }
     * 
     */
    public UnknownTeacher createUnknownTeacher() {
        return new UnknownTeacher();
    }

    /**
     * Create an instance of {@link GetAdvisorStudentResponse }
     * 
     */
    public GetAdvisorStudentResponse createGetAdvisorStudentResponse() {
        return new GetAdvisorStudentResponse();
    }

    /**
     * Create an instance of {@link AdvisorStudent }
     * 
     */
    public AdvisorStudent createAdvisorStudent() {
        return new AdvisorStudent();
    }

    /**
     * Create an instance of {@link GetDepartmentList }
     * 
     */
    public GetDepartmentList createGetDepartmentList() {
        return new GetDepartmentList();
    }

    /**
     * Create an instance of {@link GetTeacher }
     * 
     */
    public GetTeacher createGetTeacher() {
        return new GetTeacher();
    }

    /**
     * Create an instance of {@link GetTeacherList }
     * 
     */
    public GetTeacherList createGetTeacherList() {
        return new GetTeacherList();
    }

    /**
     * Create an instance of {@link GetAdvisorStudent }
     * 
     */
    public GetAdvisorStudent createGetAdvisorStudent() {
        return new GetAdvisorStudent();
    }

    /**
     * Create an instance of {@link GetTeacherResponse }
     * 
     */
    public GetTeacherResponse createGetTeacherResponse() {
        return new GetTeacherResponse();
    }

    /**
     * Create an instance of {@link Teacher }
     * 
     */
    public Teacher createTeacher() {
        return new Teacher();
    }

    /**
     * Create an instance of {@link GetTeacherListResponse }
     * 
     */
    public GetTeacherListResponse createGetTeacherListResponse() {
        return new GetTeacherListResponse();
    }

    /**
     * Create an instance of {@link TeacherList }
     * 
     */
    public TeacherList createTeacherList() {
        return new TeacherList();
    }

    /**
     * Create an instance of {@link GetTeacherofSubject }
     * 
     */
    public GetTeacherofSubject createGetTeacherofSubject() {
        return new GetTeacherofSubject();
    }

    /**
     * Create an instance of {@link AcademicYear }
     * 
     */
    public AcademicYear createAcademicYear() {
        return new AcademicYear();
    }

    /**
     * Create an instance of {@link Semesters }
     * 
     */
    public Semesters createSemesters() {
        return new Semesters();
    }

}
