//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.17 at 08:04:19 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www1.reg.kmitl.ac.th/service/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.buckwa.ws.newws.oxm;
