//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.17 at 08:04:19 PM ICT 
//


package com.buckwa.ws.newws.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for subject complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="subject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subject_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subject_tname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subject_ename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="credit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lect_hr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prac_hr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="self_hr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prerequisite" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="detail" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lock_ed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="precondition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subject_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="credit_cal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="last_thesis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="degree" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "subject", propOrder = {
    "subjectId",
    "subjectTname",
    "subjectEname",
    "credit",
    "lectHr",
    "pracHr",
    "selfHr",
    "prerequisite",
    "detail",
    "lockEd",
    "precondition",
    "status",
    "subjectType",
    "creditCal",
    "lastThesis",
    "degree"
})
public class Subject {

    @XmlElement(name = "subject_id")
    protected String subjectId;
    @XmlElement(name = "subject_tname")
    protected String subjectTname;
    @XmlElement(name = "subject_ename")
    protected String subjectEname;
    protected String credit;
    @XmlElement(name = "lect_hr")
    protected String lectHr;
    @XmlElement(name = "prac_hr")
    protected String pracHr;
    @XmlElement(name = "self_hr")
    protected String selfHr;
    protected String prerequisite;
    protected String detail;
    @XmlElement(name = "lock_ed")
    protected String lockEd;
    protected String precondition;
    protected String status;
    @XmlElement(name = "subject_type")
    protected String subjectType;
    @XmlElement(name = "credit_cal")
    protected String creditCal;
    @XmlElement(name = "last_thesis")
    protected String lastThesis;
    protected Integer degree;

    /**
     * Gets the value of the subjectId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * Sets the value of the subjectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectId(String value) {
        this.subjectId = value;
    }

    /**
     * Gets the value of the subjectTname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectTname() {
        return subjectTname;
    }

    /**
     * Sets the value of the subjectTname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectTname(String value) {
        this.subjectTname = value;
    }

    /**
     * Gets the value of the subjectEname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectEname() {
        return subjectEname;
    }

    /**
     * Sets the value of the subjectEname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectEname(String value) {
        this.subjectEname = value;
    }

    /**
     * Gets the value of the credit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCredit() {
        return credit;
    }

    /**
     * Sets the value of the credit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCredit(String value) {
        this.credit = value;
    }

    /**
     * Gets the value of the lectHr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLectHr() {
        return lectHr;
    }

    /**
     * Sets the value of the lectHr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLectHr(String value) {
        this.lectHr = value;
    }

    /**
     * Gets the value of the pracHr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPracHr() {
        return pracHr;
    }

    /**
     * Sets the value of the pracHr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPracHr(String value) {
        this.pracHr = value;
    }

    /**
     * Gets the value of the selfHr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelfHr() {
        return selfHr;
    }

    /**
     * Sets the value of the selfHr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelfHr(String value) {
        this.selfHr = value;
    }

    /**
     * Gets the value of the prerequisite property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrerequisite() {
        return prerequisite;
    }

    /**
     * Sets the value of the prerequisite property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrerequisite(String value) {
        this.prerequisite = value;
    }

    /**
     * Gets the value of the detail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetail() {
        return detail;
    }

    /**
     * Sets the value of the detail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetail(String value) {
        this.detail = value;
    }

    /**
     * Gets the value of the lockEd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLockEd() {
        return lockEd;
    }

    /**
     * Sets the value of the lockEd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLockEd(String value) {
        this.lockEd = value;
    }

    /**
     * Gets the value of the precondition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrecondition() {
        return precondition;
    }

    /**
     * Sets the value of the precondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrecondition(String value) {
        this.precondition = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the subjectType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectType() {
        return subjectType;
    }

    /**
     * Sets the value of the subjectType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectType(String value) {
        this.subjectType = value;
    }

    /**
     * Gets the value of the creditCal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreditCal() {
        return creditCal;
    }

    /**
     * Sets the value of the creditCal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreditCal(String value) {
        this.creditCal = value;
    }

    /**
     * Gets the value of the lastThesis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastThesis() {
        return lastThesis;
    }

    /**
     * Sets the value of the lastThesis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastThesis(String value) {
        this.lastThesis = value;
    }

    /**
     * Gets the value of the degree property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDegree() {
        return degree;
    }

    /**
     * Sets the value of the degree property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDegree(Integer value) {
        this.degree = value;
    }

}
