//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.07 at 11:50:04 PM ICT 
//


package com.buckwa.ws.chum.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for teacher complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="teacher">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="teacher_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="user_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="faculty_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="department_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="prename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="t_prename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="teacher_tname" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="e_prename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="teacher_ename" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="degree" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="position" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="person_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="level" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="citizen_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="advise_status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="alive" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "teacher", propOrder = {
    "teacherId",
    "userId",
    "facultyId",
    "departmentId",
    "prename",
    "tPrename",
    "teacherTname",
    "ePrename",
    "teacherEname",
    "degree",
    "position",
    "type",
    "personId",
    "level",
    "citizenId",
    "adviseStatus",
    "alive"
})
public class Teacher {

    @XmlElement(name = "teacher_id")
    protected String teacherId;
    @XmlElement(name = "user_id")
    protected String userId;
    @XmlElement(name = "faculty_id")
    protected String facultyId;
    @XmlElement(name = "department_id")
    protected String departmentId;
    protected String prename;
    @XmlElement(name = "t_prename")
    protected String tPrename;
    @XmlElement(name = "teacher_tname")
    protected String teacherTname;
    @XmlElement(name = "e_prename")
    protected String ePrename;
    @XmlElement(name = "teacher_ename")
    protected String teacherEname;
    protected String degree;
    protected String position;
    protected String type;
    @XmlElement(name = "person_id")
    protected String personId;
    protected String level;
    @XmlElement(name = "citizen_id")
    protected String citizenId;
    @XmlElement(name = "advise_status")
    protected String adviseStatus;
    protected String alive;

    /**
     * Gets the value of the teacherId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * Sets the value of the teacherId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeacherId(String value) {
        this.teacherId = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the facultyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacultyId() {
        return facultyId;
    }

    /**
     * Sets the value of the facultyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacultyId(String value) {
        this.facultyId = value;
    }

    /**
     * Gets the value of the departmentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * Sets the value of the departmentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentId(String value) {
        this.departmentId = value;
    }

    /**
     * Gets the value of the prename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrename() {
        return prename;
    }

    /**
     * Sets the value of the prename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrename(String value) {
        this.prename = value;
    }

    /**
     * Gets the value of the tPrename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTPrename() {
        return tPrename;
    }

    /**
     * Sets the value of the tPrename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTPrename(String value) {
        this.tPrename = value;
    }

    /**
     * Gets the value of the teacherTname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeacherTname() {
        return teacherTname;
    }

    /**
     * Sets the value of the teacherTname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeacherTname(String value) {
        this.teacherTname = value;
    }

    /**
     * Gets the value of the ePrename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEPrename() {
        return ePrename;
    }

    /**
     * Sets the value of the ePrename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEPrename(String value) {
        this.ePrename = value;
    }

    /**
     * Gets the value of the teacherEname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeacherEname() {
        return teacherEname;
    }

    /**
     * Sets the value of the teacherEname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeacherEname(String value) {
        this.teacherEname = value;
    }

    /**
     * Gets the value of the degree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDegree() {
        return degree;
    }

    /**
     * Sets the value of the degree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDegree(String value) {
        this.degree = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosition(String value) {
        this.position = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the personId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the personId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonId(String value) {
        this.personId = value;
    }

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLevel(String value) {
        this.level = value;
    }

    /**
     * Gets the value of the citizenId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCitizenId() {
        return citizenId;
    }

    /**
     * Sets the value of the citizenId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCitizenId(String value) {
        this.citizenId = value;
    }

    /**
     * Gets the value of the adviseStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdviseStatus() {
        return adviseStatus;
    }

    /**
     * Sets the value of the adviseStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdviseStatus(String value) {
        this.adviseStatus = value;
    }

    /**
     * Gets the value of the alive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlive() {
        return alive;
    }

    /**
     * Sets the value of the alive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlive(String value) {
        this.alive = value;
    }

}
