//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.09.07 at 06:05:19 PM ICT 
//


package com.buckwa.ws.oxm;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.buckwa.ws.oxm package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.buckwa.ws.oxm
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WrapperText }
     * 
     */
    public WrapperText createWrapperText() {
        return new WrapperText();
    }

    /**
     * Create an instance of {@link Teacher }
     * 
     */
    public Teacher createTeacher() {
        return new Teacher();
    }

    /**
     * Create an instance of {@link GetListTeachersResponse }
     * 
     */
    public GetListTeachersResponse createGetListTeachersResponse() {
        return new GetListTeachersResponse();
    }

    /**
     * Create an instance of {@link GetListTeachers }
     * 
     */
    public GetListTeachers createGetListTeachers() {
        return new GetListTeachers();
    }

}
