//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.22 at 07:02:58 PM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://161.246.85.61/registrar/service/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.buckwa.ws.newws.oxm;
