//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.09.22 at 07:02:58 PM ICT 
//


package com.buckwa.ws.newws.oxm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for teachTable complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="teachTable">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="faculty_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="department_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="curr_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="program" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subject_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="semester" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="class" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="section" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="teacher_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lect_or_prac" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="teach_day" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="teach_time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="teach_time2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="subj_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="sect" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="closed" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="branch_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="admis_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="term_admis" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="student_total" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="degree" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "teachTable", propOrder = {
    "facultyId",
    "departmentId",
    "currId",
    "program",
    "subjectId",
    "semester",
    "year",
    "clazz",
    "section",
    "teacherId",
    "lectOrPrac",
    "teachDay",
    "teachTime",
    "teachTime2",
    "subjType",
    "sect",
    "closed",
    "branchId",
    "admisType",
    "termAdmis",
    "studentTotal",
    "degree"
})
public class TeachTable {

    @XmlElement(name = "faculty_id")
    protected String facultyId;
    @XmlElement(name = "department_id")
    protected String departmentId;
    @XmlElement(name = "curr_id")
    protected String currId;
    protected String program;
    @XmlElement(name = "subject_id")
    protected String subjectId;
    protected String semester;
    protected String year;
    @XmlElement(name = "class")
    protected String clazz;
    protected String section;
    @XmlElement(name = "teacher_id")
    protected String teacherId;
    @XmlElement(name = "lect_or_prac")
    protected String lectOrPrac;
    @XmlElement(name = "teach_day")
    protected String teachDay;
    @XmlElement(name = "teach_time")
    protected String teachTime;
    @XmlElement(name = "teach_time2")
    protected String teachTime2;
    @XmlElement(name = "subj_type")
    protected String subjType;
    protected String sect;
    protected String closed;
    @XmlElement(name = "branch_id")
    protected String branchId;
    @XmlElement(name = "admis_type")
    protected String admisType;
    @XmlElement(name = "term_admis")
    protected String termAdmis;
    @XmlElement(name = "student_total")
    protected Integer studentTotal;
    protected Integer degree;

    /**
     * Gets the value of the facultyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFacultyId() {
        return facultyId;
    }

    /**
     * Sets the value of the facultyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFacultyId(String value) {
        this.facultyId = value;
    }

    /**
     * Gets the value of the departmentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepartmentId() {
        return departmentId;
    }

    /**
     * Sets the value of the departmentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepartmentId(String value) {
        this.departmentId = value;
    }

    /**
     * Gets the value of the currId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrId() {
        return currId;
    }

    /**
     * Sets the value of the currId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrId(String value) {
        this.currId = value;
    }

    /**
     * Gets the value of the program property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProgram() {
        return program;
    }

    /**
     * Sets the value of the program property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProgram(String value) {
        this.program = value;
    }

    /**
     * Gets the value of the subjectId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjectId() {
        return subjectId;
    }

    /**
     * Sets the value of the subjectId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjectId(String value) {
        this.subjectId = value;
    }

    /**
     * Gets the value of the semester property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSemester() {
        return semester;
    }

    /**
     * Sets the value of the semester property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSemester(String value) {
        this.semester = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setYear(String value) {
        this.year = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the section property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection() {
        return section;
    }

    /**
     * Sets the value of the section property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection(String value) {
        this.section = value;
    }

    /**
     * Gets the value of the teacherId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeacherId() {
        return teacherId;
    }

    /**
     * Sets the value of the teacherId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeacherId(String value) {
        this.teacherId = value;
    }

    /**
     * Gets the value of the lectOrPrac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLectOrPrac() {
        return lectOrPrac;
    }

    /**
     * Sets the value of the lectOrPrac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLectOrPrac(String value) {
        this.lectOrPrac = value;
    }

    /**
     * Gets the value of the teachDay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeachDay() {
        return teachDay;
    }

    /**
     * Sets the value of the teachDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeachDay(String value) {
        this.teachDay = value;
    }

    /**
     * Gets the value of the teachTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeachTime() {
        return teachTime;
    }

    /**
     * Sets the value of the teachTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeachTime(String value) {
        this.teachTime = value;
    }

    /**
     * Gets the value of the teachTime2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeachTime2() {
        return teachTime2;
    }

    /**
     * Sets the value of the teachTime2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeachTime2(String value) {
        this.teachTime2 = value;
    }

    /**
     * Gets the value of the subjType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubjType() {
        return subjType;
    }

    /**
     * Sets the value of the subjType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubjType(String value) {
        this.subjType = value;
    }

    /**
     * Gets the value of the sect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSect() {
        return sect;
    }

    /**
     * Sets the value of the sect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSect(String value) {
        this.sect = value;
    }

    /**
     * Gets the value of the closed property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClosed() {
        return closed;
    }

    /**
     * Sets the value of the closed property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClosed(String value) {
        this.closed = value;
    }

    /**
     * Gets the value of the branchId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchId() {
        return branchId;
    }

    /**
     * Sets the value of the branchId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchId(String value) {
        this.branchId = value;
    }

    /**
     * Gets the value of the admisType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmisType() {
        return admisType;
    }

    /**
     * Sets the value of the admisType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmisType(String value) {
        this.admisType = value;
    }

    /**
     * Gets the value of the termAdmis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTermAdmis() {
        return termAdmis;
    }

    /**
     * Sets the value of the termAdmis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTermAdmis(String value) {
        this.termAdmis = value;
    }

    /**
     * Gets the value of the studentTotal property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStudentTotal() {
        return studentTotal;
    }

    /**
     * Sets the value of the studentTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStudentTotal(Integer value) {
        this.studentTotal = value;
    }

    /**
     * Gets the value of the degree property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDegree() {
        return degree;
    }

    /**
     * Sets the value of the degree property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDegree(Integer value) {
        this.degree = value;
    }

}
